<a href="https://www.kaggle.com/code/aabhak02/final-detector?scriptVersionId=312677039" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
import os

# ------------------------
# GPU check (no memory growth)
# ------------------------
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("GPU ready:", gpus[0])
else:
    print("Using CPU")

# ------------------------
# Data pipeline
# ------------------------
train_dir = '/kaggle/input/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/train'
test_dir  = '/kaggle/input/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/test'

datagen = ImageDataGenerator(rescale=1./255)

train_gen = datagen.flow_from_directory(
    train_dir,
    target_size=(32,32),
    batch_size=32,
    class_mode='binary'
)

test_gen = datagen.flow_from_directory(
    test_dir,
    target_size=(32,32),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

# ------------------------
# Tiny CNN
# ------------------------
model = Sequential([
    Conv2D(16,(3,3),activation='relu',input_shape=(32,32,3)),
    MaxPooling2D(2,2),
    Conv2D(32,(3,3),activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(64,activation='relu'),
    Dropout(0.3),
    Dense(1,activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# ------------------------
# Train
# ------------------------
model.fit(train_gen, validation_data=test_gen, epochs=5)

# ------------------------
# Predict
# ------------------------
preds = model.predict(test_gen)
print(preds[:10])

# ------------------------
# Save trained model
# ------------------------
MODEL_DIR = '/kaggle/working/models'
os.makedirs(MODEL_DIR, exist_ok=True)
MODEL_PATH = os.path.join(MODEL_DIR, 'my_model.h5')

model.save(MODEL_PATH)
print(f"Model saved at: {MODEL_PATH}")

2026-04-18 18:47:21.412418: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1776538041.595813      23 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1776538041.646530      23 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1776538042.067077      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776538042.067120      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776538042.067123      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776538042.067126      23 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

GPU ready: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
Found 100000 images belonging to 2 classes.
Found 20000 images belonging to 2 classes.

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1776538174.528943      23 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15511 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 30, 30, 16)     │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 15, 15, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 13, 13, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 6, 6, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │        73,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 78,945 (308.38 KB)

 Trainable params: 78,945 (308.38 KB)

 Non-trainable params: 0 (0.00 B)

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()

Epoch 1/5

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1776538178.060935      82 service.cc:152] XLA service 0x7da590002e20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1776538178.060972      82 service.cc:160]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
I0000 00:00:1776538178.434392      82 cuda_dnn.cc:529] Loaded cuDNN version 91002

   1/3125 ━━━━━━━━━━━━━━━━━━━━ 3:33:44 4s/step - accuracy: 0.4062 - loss: 0.6993

I0000 00:00:1776538180.634462      82 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

3125/3125 ━━━━━━━━━━━━━━━━━━━━ 955s 305ms/step - accuracy: 0.7736 - loss: 0.4595 - val_accuracy: 0.8885 - val_loss: 0.2695
Epoch 2/5
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 269s 86ms/step - accuracy: 0.8927 - loss: 0.2653 - val_accuracy: 0.9037 - val_loss: 0.2362
Epoch 3/5
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 259s 83ms/step - accuracy: 0.9121 - loss: 0.2229 - val_accuracy: 0.9024 - val_loss: 0.2423
Epoch 4/5
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 257s 82ms/step - accuracy: 0.9209 - loss: 0.2030 - val_accuracy: 0.9168 - val_loss: 0.2062
Epoch 5/5
3125/3125 ━━━━━━━━━━━━━━━━━━━━ 263s 84ms/step - accuracy: 0.9256 - loss: 0.1904 - val_accuracy: 0.9221 - val_loss: 0.1962
625/625 ━━━━━━━━━━━━━━━━━━━━ 23s 36ms/step

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

[[5.3190957e-05]
 [9.4379969e-03]
 [8.8640221e-04]
 [9.3405036e-04]
 [1.3643313e-03]
 [1.4647981e-02]
 [1.3355493e-04]
 [8.5616119e-09]
 [2.5700710e-03]
 [4.7702473e-02]]
Model saved at: /kaggle/working/models/my_model.h5

In [2]:
import os
import csv
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# ------------------------
# Enable GPU
# ------------------------
import tensorflow as tf

print("GPUs available:", tf.config.list_physical_devices('GPU'))
# ------------------------
# Paths
# ------------------------
TEST_DIR = "/kaggle/input/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/test/REAL"
MODEL_PATH = "/kaggle/input/models/aabhak02/mymodel-h5/keras/default/1/my_model.h5"

IMG_SIZE = (32, 32)
BATCH_SIZE = 128

# ------------------------
# Load model
# ------------------------
model = load_model(MODEL_PATH)

# ------------------------
# Collect images
# ------------------------
test_files = [
    f for f in os.listdir(TEST_DIR)
    if os.path.isfile(os.path.join(TEST_DIR, f))
]

print("Total images:", len(test_files))

# ------------------------
# Preprocess function
# ------------------------
def load_batch(files):
    batch = []
    for f in files:
        img_path = os.path.join(TEST_DIR, f)
        img = image.load_img(img_path, target_size=IMG_SIZE)
        img = image.img_to_array(img) / 255.0
        batch.append(img)
    return np.array(batch)

# ------------------------
# CSV output
# ------------------------
csv_path = "/kaggle/working/predictions_real.csv"

with open(csv_path, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["image_name", "prediction", "probability"])

    # Process in batches
    for i in range(0, len(test_files), BATCH_SIZE):

        batch_files = test_files[i:i+BATCH_SIZE]
        batch_images = load_batch(batch_files)

        preds = model.predict(batch_images, verbose=0)

        for img_name, pred in zip(batch_files, preds):
            prob = float(pred[0])
            label = "REAL" if prob > 0.5 else "AI"

            writer.writerow([img_name, label, prob])

        print(f"Processed {min(i+BATCH_SIZE, len(test_files))}/{len(test_files)}")

print("CSV saved:", csv_path)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

GPUs available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Total images: 10000
Processed 128/10000
Processed 256/10000
Processed 384/10000
Processed 512/10000
Processed 640/10000
Processed 768/10000
Processed 896/10000
Processed 1024/10000
Processed 1152/10000
Processed 1280/10000
Processed 1408/10000
Processed 1536/10000
Processed 1664/10000
Processed 1792/10000
Processed 1920/10000
Processed 2048/10000
Processed 2176/10000
Processed 2304/10000
Processed 2432/10000
Processed 2560/10000
Processed 2688/10000
Processed 2816/10000
Processed 2944/10000
Processed 3072/10000
Processed 3200/10000
Processed 3328/10000
Processed 3456/10000
Processed 3584/10000
Processed 3712/10000
Processed 3840/10000
Processed 3968/10000
Processed 4096/10000
Processed 4224/10000
Processed 4352/10000
Processed 4480/10000
Processed 4608/10000
Processed 4736/10000
Processed 4864/10000
Processed 4992/10000
Processed 5120/10000
Processed 5248/10000
Processed 5376/10000
Processed 5504/10000
Processed 5632/10000
Processed 5760/10000
Processed 5888/10000
Processed 6016/10000
Processed 6144/10000
Processed 6272/10000
Processed 6400/10000
Processed 6528/10000
Processed 6656/10000
Processed 6784/10000
Processed 6912/10000
Processed 7040/10000
Processed 7168/10000
Processed 7296/10000
Processed 7424/10000
Processed 7552/10000
Processed 7680/10000
Processed 7808/10000
Processed 7936/10000
Processed 8064/10000
Processed 8192/10000
Processed 8320/10000
Processed 8448/10000
Processed 8576/10000
Processed 8704/10000
Processed 8832/10000
Processed 8960/10000
Processed 9088/10000
Processed 9216/10000
Processed 9344/10000
Processed 9472/10000
Processed 9600/10000
Processed 9728/10000
Processed 9856/10000
Processed 9984/10000
Processed 10000/10000
CSV saved: /kaggle/working/predictions_real.csv

In [3]:
import os
import csv
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# ------------------------
# Enable GPU

print("GPUs available:", tf.config.list_physical_devices('GPU'))

# ------------------------
# Paths
# ------------------------
TEST_DIR = "/kaggle/input/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/test/FAKE"
MODEL_PATH = "/kaggle/input/models/aabhak02/mymodel-h5/keras/default/1/my_model.h5"

IMG_SIZE = (32, 32)
BATCH_SIZE = 128

# ------------------------
# Load model
# ------------------------
model = load_model(MODEL_PATH)

# ------------------------
# Collect images
# ------------------------
test_files = [
    f for f in os.listdir(TEST_DIR)
    if os.path.isfile(os.path.join(TEST_DIR, f))
]

print("Total images:", len(test_files))

# ------------------------
# Preprocess function
# ------------------------
def load_batch(files):
    batch = []
    for f in files:
        img_path = os.path.join(TEST_DIR, f)
        img = image.load_img(img_path, target_size=IMG_SIZE)
        img = image.img_to_array(img) / 255.0
        batch.append(img)
    return np.array(batch)

# ------------------------
# CSV output
# ------------------------
csv_path = "/kaggle/working/predictions_ai.csv"

with open(csv_path, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["image_name", "prediction", "probability"])

    # Process in batches
    for i in range(0, len(test_files), BATCH_SIZE):

        batch_files = test_files[i:i+BATCH_SIZE]
        batch_images = load_batch(batch_files)

        preds = model.predict(batch_images, verbose=0)

        for img_name, pred in zip(batch_files, preds):
            prob = float(pred[0])
            label = "REAL" if prob > 0.5 else "AI"

            writer.writerow([img_name, label, prob])

        print(f"Processed {min(i+BATCH_SIZE, len(test_files))}/{len(test_files)}")

print("CSV saved:", csv_path)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

GPUs available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Total images: 10000
Processed 128/10000
Processed 256/10000
Processed 384/10000
Processed 512/10000
Processed 640/10000
Processed 768/10000
Processed 896/10000
Processed 1024/10000
Processed 1152/10000
Processed 1280/10000
Processed 1408/10000
Processed 1536/10000
Processed 1664/10000
Processed 1792/10000
Processed 1920/10000
Processed 2048/10000
Processed 2176/10000
Processed 2304/10000
Processed 2432/10000
Processed 2560/10000
Processed 2688/10000
Processed 2816/10000
Processed 2944/10000
Processed 3072/10000
Processed 3200/10000
Processed 3328/10000
Processed 3456/10000
Processed 3584/10000
Processed 3712/10000
Processed 3840/10000
Processed 3968/10000
Processed 4096/10000
Processed 4224/10000
Processed 4352/10000
Processed 4480/10000
Processed 4608/10000
Processed 4736/10000
Processed 4864/10000
Processed 4992/10000
Processed 5120/10000
Processed 5248/10000
Processed 5376/10000
Processed 5504/10000
Processed 5632/10000
Processed 5760/10000
Processed 5888/10000
Processed 6016/10000
Processed 6144/10000
Processed 6272/10000
Processed 6400/10000
Processed 6528/10000
Processed 6656/10000
Processed 6784/10000
Processed 6912/10000
Processed 7040/10000
Processed 7168/10000
Processed 7296/10000
Processed 7424/10000
Processed 7552/10000
Processed 7680/10000
Processed 7808/10000
Processed 7936/10000
Processed 8064/10000
Processed 8192/10000
Processed 8320/10000
Processed 8448/10000
Processed 8576/10000
Processed 8704/10000
Processed 8832/10000
Processed 8960/10000
Processed 9088/10000
Processed 9216/10000
Processed 9344/10000
Processed 9472/10000
Processed 9600/10000
Processed 9728/10000
Processed 9856/10000
Processed 9984/10000
Processed 10000/10000
CSV saved: /kaggle/working/predictions_ai.csv

In [4]:
import os
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# ------------------------
# Path and params
# ------------------------
TEST_DIR = "/kaggle/input/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/test/FAKE"  # your folder here
IMG_SIZE = (32, 32)  # same as your CNN input

# ------------------------
# Load the saved model
# ------------------------
model = load_model('/kaggle/input/models/aabhak02/mymodel-h5/keras/default/1/my_model.h5')

# ------------------------
# Preprocess function
# ------------------------
def preprocess_img(img_path):
    img = image.load_img(img_path, target_size=IMG_SIZE)
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

# ------------------------
# Predict all images in the folder
# ------------------------
test_files = [f for f in os.listdir(TEST_DIR) if os.path.isfile(os.path.join(TEST_DIR, f))]

for img_file in test_files:
    img_path = os.path.join(TEST_DIR, img_file)
    img_input = preprocess_img(img_path)
    pred = model.predict(img_input)[0][0]  # sigmoid output
    label = "REAL" if pred > 0.5 else "AI"
    print(f"{img_file}: {label} ({pred:.5f})")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 415ms/step
943 (5).jpg: REAL (0.96633)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
534 (7).jpg: AI (0.00001)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
81 (2).jpg: AI (0.09282)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
869 (9).jpg: AI (0.20732)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
610 (10).jpg: AI (0.00077)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
623.jpg: AI (0.45220)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
697 (8).jpg: AI (0.04089)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
194 (4).jpg: AI (0.28234)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
435 (3).jpg: REAL (0.97613)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
380 (3).jpg: AI (0.33813)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
491 (8).jpg: AI (0.05006)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
680 (8).jpg: AI (0.04487)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
323 (5).jpg: AI (0.00468)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
219 (7).jpg: AI (0.00009)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
833 (7).jpg: AI (0.01221)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
350 (5).jpg: AI (0.00107)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
184 (5).jpg: AI (0.24633)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
410 (5).jpg: AI (0.42581)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
462 (7).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
792 (6).jpg: REAL (0.53920)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
905 (5).jpg: AI (0.08136)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
902 (4).jpg: AI (0.00567)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
759 (10).jpg: AI (0.17927)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
338 (2).jpg: AI (0.40449)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
294 (6).jpg: AI (0.00233)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
617 (2).jpg: AI (0.00057)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
859 (8).jpg: AI (0.05975)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
734 (6).jpg: AI (0.00185)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
722 (3).jpg: REAL (0.99717)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
588 (2).jpg: AI (0.00029)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
5 (6).jpg: REAL (0.87494)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
764.jpg: AI (0.05405)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
430 (2).jpg: AI (0.02379)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
95 (7).jpg: AI (0.00002)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
138 (2).jpg: AI (0.08451)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
181 (7).jpg: AI (0.00298)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
766 (2).jpg: AI (0.00104)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
428 (8).jpg: AI (0.00339)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
675 (8).jpg: REAL (0.90547)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
457 (4).jpg: AI (0.05516)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
254 (4).jpg: AI (0.00024)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
771.jpg: AI (0.20406)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
208.jpg: AI (0.01542)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
863 (4).jpg: AI (0.03322)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
138 (10).jpg: AI (0.11787)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
497 (8).jpg: AI (0.00334)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
525 (8).jpg: AI (0.02981)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
895 (9).jpg: AI (0.00002)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
824 (8).jpg: REAL (0.79918)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
463 (4).jpg: AI (0.01855)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
153 (6).jpg: AI (0.07019)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
639 (3).jpg: AI (0.00127)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
206 (3).jpg: REAL (0.99862)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
820.jpg: AI (0.00008)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
102 (6).jpg: AI (0.00382)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
934 (3).jpg: AI (0.01181)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
125 (8).jpg: AI (0.14976)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
175 (4).jpg: AI (0.06400)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
437 (9).jpg: REAL (0.62667)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
250 (10).jpg: AI (0.01571)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
495 (8).jpg: AI (0.15563)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
987 (5).jpg: AI (0.07013)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
351 (10).jpg: AI (0.17344)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
871 (5).jpg: AI (0.02756)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
591 (3).jpg: AI (0.03269)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
986 (7).jpg: AI (0.00005)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
111 (2).jpg: AI (0.00969)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
965 (4).jpg: AI (0.01003)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
221 (2).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
303 (2).jpg: REAL (0.92775)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
641 (4).jpg: AI (0.00026)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
473.jpg: AI (0.01383)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
145 (9).jpg: AI (0.03482)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
906 (8).jpg: AI (0.32335)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
108 (7).jpg: AI (0.03777)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
289 (5).jpg: AI (0.01617)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
895 (4).jpg: AI (0.00223)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
420 (2).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
94 (3).jpg: AI (0.01421)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
218 (7).jpg: AI (0.00261)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
807 (3).jpg: AI (0.03718)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
825 (3).jpg: AI (0.00030)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
748 (10).jpg: AI (0.01840)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
147 (9).jpg: AI (0.00144)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
185 (4).jpg: AI (0.00036)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
915 (4).jpg: AI (0.07806)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
166 (5).jpg: REAL (0.94174)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
780 (7).jpg: AI (0.00002)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
258 (8).jpg: AI (0.00091)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
162 (9).jpg: AI (0.04769)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
217 (6).jpg: AI (0.00691)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
245 (10).jpg: AI (0.00027)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
523 (4).jpg: AI (0.00007)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
511 (10).jpg: AI (0.48071)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
751 (3).jpg: AI (0.05878)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
13 (6).jpg: AI (0.03714)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
250 (2).jpg: AI (0.00207)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
260 (5).jpg: AI (0.00034)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
965 (5).jpg: AI (0.22277)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
936 (6).jpg: AI (0.07061)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
948 (10).jpg: AI (0.00176)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
968 (6).jpg: AI (0.04849)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
537 (6).jpg: AI (0.00704)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
534 (3).jpg: AI (0.26677)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
280 (2).jpg: AI (0.08720)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
695 (5).jpg: AI (0.02813)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
892 (3).jpg: REAL (0.87881)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
505 (9).jpg: REAL (0.95229)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
802 (7).jpg: AI (0.00233)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
243 (9).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
768 (10).jpg: REAL (0.95416)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
10 (8).jpg: AI (0.00168)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
137 (5).jpg: AI (0.00087)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
23 (8).jpg: AI (0.00357)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
387 (8).jpg: REAL (0.54180)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
438 (7).jpg: AI (0.02306)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
633 (2).jpg: AI (0.00080)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
233 (5).jpg: AI (0.00008)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
797 (6).jpg: AI (0.27835)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
811 (7).jpg: AI (0.00029)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
169 (3).jpg: AI (0.27785)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
568 (6).jpg: AI (0.01745)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
376 (10).jpg: AI (0.22765)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
511 (8).jpg: AI (0.00264)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
645 (8).jpg: AI (0.17254)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
882 (6).jpg: AI (0.01464)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
169 (4).jpg: AI (0.04824)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
782 (10).jpg: AI (0.00024)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
227 (7).jpg: AI (0.00344)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
333.jpg: AI (0.08362)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
171 (3).jpg: REAL (0.54603)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
172 (6).jpg: AI (0.01140)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
537.jpg: AI (0.01321)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
738 (4).jpg: REAL (0.56164)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
975 (3).jpg: AI (0.13377)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
8 (7).jpg: AI (0.00356)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
287 (7).jpg: AI (0.00001)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
80 (5).jpg: AI (0.00131)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
792 (2).jpg: AI (0.00065)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
975 (10).jpg: AI (0.03742)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
341 (2).jpg: AI (0.28900)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
45.jpg: AI (0.01229)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
771 (2).jpg: REAL (0.62427)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
365 (6).jpg: AI (0.07101)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
41 (4).jpg: AI (0.38685)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
843 (4).jpg: AI (0.02780)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
358 (3).jpg: AI (0.47124)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
103 (6).jpg: AI (0.00422)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
369.jpg: AI (0.00050)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
355 (9).jpg: AI (0.06297)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
88 (6).jpg: AI (0.00073)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
407 (5).jpg: REAL (0.92821)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
56.jpg: REAL (0.72241)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
589 (4).jpg: AI (0.00007)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
308 (2).jpg: AI (0.00005)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
660 (9).jpg: AI (0.03194)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
654.jpg: AI (0.03705)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
473 (8).jpg: AI (0.00072)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
92 (6).jpg: AI (0.22546)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
275 (4).jpg: AI (0.00704)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
89.jpg: AI (0.00449)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
852 (2).jpg: AI (0.00045)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
821 (4).jpg: AI (0.04192)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
878 (6).jpg: AI (0.00160)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
806 (9).jpg: REAL (0.78943)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
958 (10).jpg: AI (0.11272)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
318 (8).jpg: AI (0.00023)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
638 (4).jpg: AI (0.00213)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
883 (3).jpg: AI (0.01119)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
20.jpg: AI (0.00567)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
198 (9).jpg: REAL (0.61201)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
201 (8).jpg: AI (0.00064)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
109 (10).jpg: AI (0.00394)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
544 (5).jpg: REAL (0.86975)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
506 (4).jpg: AI (0.14753)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
597 (4).jpg: AI (0.13171)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
185 (10).jpg: AI (0.00004)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
617 (9).jpg: AI (0.09286)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
275.jpg: AI (0.00713)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
472 (5).jpg: AI (0.05368)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
409 (10).jpg: AI (0.01275)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
702 (8).jpg: AI (0.09236)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
573 (8).jpg: AI (0.04574)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
785.jpg: AI (0.07006)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
378 (3).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
646 (4).jpg: AI (0.02898)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
156 (5).jpg: AI (0.00021)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
819 (8).jpg: AI (0.42343)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
831 (4).jpg: AI (0.37949)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
996 (9).jpg: AI (0.00126)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
733 (6).jpg: AI (0.00315)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
734 (2).jpg: AI (0.00001)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
647 (6).jpg: AI (0.21309)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
212.jpg: AI (0.05394)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
848 (8).jpg: AI (0.00014)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
236 (6).jpg: AI (0.00003)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
928 (5).jpg: AI (0.00016)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
239.jpg: AI (0.07595)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
42 (9).jpg: AI (0.01677)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
792.jpg: AI (0.00044)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
251 (9).jpg: AI (0.00024)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
41 (10).jpg: AI (0.00417)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
977 (9).jpg: REAL (0.82337)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
990 (10).jpg: AI (0.05360)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
657 (2).jpg: AI (0.02500)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
192 (3).jpg: AI (0.00057)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
853 (7).jpg: AI (0.00059)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
239 (4).jpg: AI (0.00563)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
474 (4).jpg: REAL (0.98587)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
648 (10).jpg: AI (0.30929)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
829 (3).jpg: REAL (0.96723)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
646 (5).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
652 (8).jpg: AI (0.00092)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
858 (2).jpg: REAL (0.98948)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
58.jpg: AI (0.00007)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
685 (6).jpg: AI (0.00485)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
229 (4).jpg: AI (0.16224)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
319 (2).jpg: AI (0.00008)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
214 (6).jpg: AI (0.00116)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
885 (8).jpg: AI (0.00468)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
927 (6).jpg: REAL (0.95835)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
36 (10).jpg: AI (0.01111)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
187 (8).jpg: AI (0.08156)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
925 (2).jpg: AI (0.00004)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
731 (3).jpg: REAL (0.79622)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
820 (9).jpg: AI (0.18549)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
163 (9).jpg: AI (0.08657)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
991 (2).jpg: AI (0.00500)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
478 (8).jpg: AI (0.00665)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
412 (3).jpg: AI (0.00055)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
822 (8).jpg: REAL (0.92609)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
246 (7).jpg: AI (0.34883)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
942 (2).jpg: AI (0.16174)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
151 (3).jpg: AI (0.22441)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
957 (9).jpg: AI (0.03776)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
150.jpg: AI (0.00233)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
886 (5).jpg: AI (0.00474)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
429 (8).jpg: AI (0.01487)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
414 (2).jpg: AI (0.00018)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
6.jpg: REAL (0.81506)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
109.jpg: AI (0.01960)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
196 (10).jpg: REAL (0.95721)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
682 (2).jpg: AI (0.03357)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
387 (10).jpg: AI (0.03832)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
773 (6).jpg: AI (0.00066)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
119 (5).jpg: AI (0.00221)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
14 (2).jpg: AI (0.00003)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
864 (7).jpg: AI (0.00074)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
862 (5).jpg: AI (0.01538)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
202 (8).jpg: AI (0.00001)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
866 (10).jpg: REAL (0.63862)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
732 (5).jpg: AI (0.41765)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
774 (8).jpg: REAL (0.92773)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
777 (9).jpg: AI (0.40864)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
134 (2).jpg: AI (0.00574)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
170 (4).jpg: AI (0.23909)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
846 (2).jpg: AI (0.00028)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
546 (7).jpg: AI (0.00532)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
197 (8).jpg: AI (0.01549)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
858 (7).jpg: AI (0.01032)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
328 (9).jpg: AI (0.00924)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
149.jpg: AI (0.03022)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
939 (3).jpg: AI (0.36752)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
272 (4).jpg: AI (0.00303)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
841 (6).jpg: AI (0.11456)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
347 (9).jpg: AI (0.28898)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
197 (9).jpg: REAL (0.89708)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
471 (3).jpg: AI (0.19684)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
616 (8).jpg: AI (0.01367)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
209 (3).jpg: AI (0.37945)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
509 (9).jpg: REAL (0.96355)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
187.jpg: AI (0.20864)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
521.jpg: AI (0.24562)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
436.jpg: REAL (0.53150)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
571 (9).jpg: REAL (0.99269)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
999 (5).jpg: AI (0.11214)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
300 (4).jpg: AI (0.02850)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
637 (2).jpg: AI (0.00029)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
977 (7).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
632 (4).jpg: AI (0.00006)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
714 (8).jpg: REAL (0.95290)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
76.jpg: AI (0.22664)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
549 (3).jpg: AI (0.00158)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
539.jpg: AI (0.11880)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
831 (10).jpg: AI (0.00272)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
99 (6).jpg: AI (0.10440)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
761 (3).jpg: AI (0.12862)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
203 (4).jpg: AI (0.05334)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
989 (3).jpg: REAL (0.57254)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
855 (6).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
108 (2).jpg: AI (0.00041)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
355.jpg: AI (0.00941)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
317 (2).jpg: AI (0.00352)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
839 (2).jpg: AI (0.36370)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
45 (2).jpg: AI (0.00083)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
698 (7).jpg: AI (0.00144)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
135 (10).jpg: AI (0.00298)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
844 (10).jpg: REAL (0.99634)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
320 (4).jpg: AI (0.00624)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
822 (2).jpg: AI (0.00001)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
410 (7).jpg: AI (0.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
181 (8).jpg: AI (0.02772)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
464 (9).jpg: AI (0.00499)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
701 (7).jpg: AI (0.06452)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
776 (8).jpg: AI (0.05127)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
85 (3).jpg: AI (0.00616)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
646 (7).jpg: AI (0.00025)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
813 (9).jpg: AI (0.00007)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
244 (10).jpg: AI (0.03386)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
968 (3).jpg: AI (0.10093)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
516.jpg: AI (0.00024)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
914 (3).jpg: AI (0.00948)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
660 (7).jpg: AI (0.00017)

In [5]:
import os
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model

# ------------------------
# Path and params
# ------------------------
TEST_DIR = "/kaggle/input/datasets/birdy654/cifake-real-and-ai-generated-synthetic-images/test/REAL"  # your folder here
IMG_SIZE = (32, 32)  # same as your CNN input

# ------------------------
# Load the saved model
# ------------------------
model = load_model('/kaggle/input/models/aabhak02/mymodel-h5/keras/default/1/my_model.h5')

# ------------------------
# Preprocess function
# ------------------------
def preprocess_img(img_path):
    img = image.load_img(img_path, target_size=IMG_SIZE)
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

# ------------------------
# Predict all images in the folder
# ------------------------
test_files = [f for f in os.listdir(TEST_DIR) if os.path.isfile(os.path.join(TEST_DIR, f))]

for img_file in test_files:
    img_path = os.path.join(TEST_DIR, img_file)
    img_input = preprocess_img(img_path)
    pred = model.predict(img_input)[0][0]  # sigmoid output
    label = "REAL" if pred > 0.5 else "AI"
    print(f"{img_file}: {label} ({pred:.5f})")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 363ms/step
0664.jpg: REAL (0.91878)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0280 (6).jpg: REAL (0.63280)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0816 (6).jpg: REAL (0.99932)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0704 (5).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0896 (9).jpg: REAL (0.99957)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0316 (3).jpg: REAL (0.99882)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0102 (3).jpg: REAL (0.98441)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0369 (4).jpg: REAL (0.99154)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0010 (4).jpg: REAL (0.99891)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0029 (10).jpg: AI (0.48608)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0235 (4).jpg: REAL (0.99986)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0178 (9).jpg: REAL (0.98086)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0407 (2).jpg: REAL (0.67335)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0348 (4).jpg: REAL (0.98981)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0733.jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0279 (10).jpg: REAL (0.98250)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0106.jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0927 (5).jpg: REAL (0.99877)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0167 (5).jpg: REAL (0.99895)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0375.jpg: REAL (0.75312)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0068 (2).jpg: REAL (0.98868)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0711 (7).jpg: REAL (0.96002)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0499 (5).jpg: REAL (0.99985)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0261 (4).jpg: REAL (0.99996)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0674 (9).jpg: REAL (0.99872)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0672 (8).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0764 (6).jpg: REAL (0.99414)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0400 (5).jpg: REAL (0.99988)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0518 (2).jpg: REAL (0.99889)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0565 (8).jpg: REAL (0.62924)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0019 (2).jpg: REAL (0.99763)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0803 (7).jpg: REAL (0.99963)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0682 (2).jpg: REAL (0.96876)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0048 (2).jpg: REAL (0.99993)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0219 (5).jpg: REAL (0.99985)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0488 (3).jpg: REAL (0.99388)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0053 (9).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0544 (4).jpg: REAL (0.99998)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0526 (7).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0492 (3).jpg: REAL (0.96692)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0695 (9).jpg: REAL (0.99962)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0980 (10).jpg: REAL (0.94545)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0942 (4).jpg: REAL (0.99974)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
0794 (3).jpg: AI (0.43264)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0262 (9).jpg: REAL (0.99991)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0895 (7).jpg: REAL (0.99908)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0334 (2).jpg: REAL (0.89938)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0407 (10).jpg: REAL (0.99272)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0587 (10).jpg: REAL (0.96141)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0128 (4).jpg: REAL (0.96611)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0103 (4).jpg: REAL (0.99781)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0351 (3).jpg: REAL (0.93617)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0577 (5).jpg: REAL (0.97444)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0914 (2).jpg: REAL (0.92062)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0097 (9).jpg: REAL (0.99965)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0915 (9).jpg: REAL (0.99707)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0872 (2).jpg: REAL (0.99987)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0285.jpg: REAL (0.99997)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0282 (2).jpg: REAL (0.99184)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0524 (4).jpg: REAL (0.84299)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0107 (9).jpg: REAL (0.99832)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0563 (2).jpg: AI (0.06270)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0299 (8).jpg: REAL (0.99941)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0379 (4).jpg: REAL (0.99743)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0518 (10).jpg: REAL (0.99986)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0286 (6).jpg: REAL (0.95207)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0952 (10).jpg: REAL (0.99854)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0108 (4).jpg: REAL (0.74589)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
0714 (10).jpg: REAL (0.99961)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0591.jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0080 (8).jpg: REAL (0.99968)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0077 (10).jpg: REAL (0.99201)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0849 (9).jpg: REAL (0.98773)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0799.jpg: REAL (0.99921)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0395 (9).jpg: REAL (0.91607)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0351 (6).jpg: AI (0.32799)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0808 (8).jpg: REAL (0.99855)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0765 (5).jpg: REAL (0.86589)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0524 (10).jpg: REAL (0.97912)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0635 (7).jpg: REAL (0.99996)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0277 (9).jpg: REAL (0.99634)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0963 (8).jpg: REAL (0.98983)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0074.jpg: REAL (0.92422)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0564 (4).jpg: REAL (0.99735)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0358 (2).jpg: REAL (0.99949)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0020 (4).jpg: REAL (0.99753)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0132 (8).jpg: REAL (0.99913)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0982 (7).jpg: REAL (0.99244)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0249 (7).jpg: REAL (0.99989)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0587 (5).jpg: REAL (0.99776)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0668 (5).jpg: REAL (0.99990)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0558 (9).jpg: REAL (0.94813)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0077.jpg: AI (0.12727)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0424 (2).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0198 (8).jpg: REAL (0.99491)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0210 (4).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0904 (5).jpg: REAL (0.99996)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0370 (3).jpg: REAL (0.99920)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0554 (2).jpg: REAL (0.99926)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0498.jpg: REAL (0.99996)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0002 (3).jpg: REAL (0.98717)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0195 (6).jpg: REAL (0.99993)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0957 (10).jpg: REAL (0.97833)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0556 (6).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0610.jpg: REAL (0.99994)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
0858 (10).jpg: REAL (0.59167)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0785 (8).jpg: REAL (0.95163)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0205 (3).jpg: REAL (0.99872)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0781 (2).jpg: REAL (0.99997)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0249 (10).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
0071 (10).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0936 (7).jpg: REAL (0.99915)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0116 (5).jpg: REAL (0.99992)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0617.jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0038 (10).jpg: REAL (0.80116)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0834 (10).jpg: REAL (0.63224)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0908 (8).jpg: REAL (0.98228)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0989 (6).jpg: REAL (0.99095)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0160 (2).jpg: REAL (0.91065)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0767 (3).jpg: REAL (0.99695)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
0743 (5).jpg: REAL (0.99967)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0899 (3).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0778 (2).jpg: REAL (0.99473)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0985 (2).jpg: REAL (0.99866)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0914 (7).jpg: REAL (0.99998)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0379 (6).jpg: REAL (0.99980)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0944 (3).jpg: REAL (0.99987)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0294 (10).jpg: REAL (0.99920)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0116 (10).jpg: REAL (0.99147)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0497 (5).jpg: REAL (0.99675)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0478 (10).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0569 (8).jpg: REAL (0.99959)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0385 (8).jpg: REAL (0.99951)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0357 (10).jpg: REAL (0.99724)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0460 (8).jpg: REAL (0.99630)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0634 (2).jpg: REAL (0.99582)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0057 (4).jpg: REAL (0.97487)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0316 (8).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0732 (2).jpg: REAL (0.98894)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0882 (6).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0606 (6).jpg: REAL (0.99821)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0294 (7).jpg: REAL (0.99461)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0813 (8).jpg: REAL (0.99515)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0888 (4).jpg: REAL (0.99864)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0522 (5).jpg: REAL (0.99877)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0226 (6).jpg: REAL (0.99996)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0269 (6).jpg: REAL (0.67338)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0426.jpg: REAL (0.99862)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0753 (5).jpg: REAL (0.99993)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0671 (7).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0958 (5).jpg: REAL (0.99932)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0382 (10).jpg: REAL (0.99463)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0683 (9).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0951 (5).jpg: REAL (0.99846)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0406 (4).jpg: REAL (0.99994)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0211 (5).jpg: REAL (0.99693)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0615 (3).jpg: REAL (0.99940)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0020 (7).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0661 (2).jpg: REAL (0.99587)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0542 (8).jpg: REAL (0.99997)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0989.jpg: REAL (0.56519)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0235.jpg: REAL (0.65603)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0273.jpg: REAL (0.99900)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0016 (8).jpg: REAL (0.99969)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0589 (9).jpg: REAL (0.99824)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0180 (2).jpg: REAL (0.99925)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0203 (2).jpg: REAL (0.97435)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0307.jpg: REAL (0.78771)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0329 (7).jpg: REAL (0.93333)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0791 (8).jpg: REAL (0.99996)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0707 (7).jpg: REAL (0.99995)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0739 (7).jpg: REAL (0.98280)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0920 (2).jpg: REAL (0.99973)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0456 (4).jpg: REAL (0.99998)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0727 (2).jpg: REAL (0.94401)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0928 (4).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0575 (5).jpg: REAL (0.99786)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0035 (2).jpg: REAL (0.98313)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
0509 (6).jpg: REAL (0.99982)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0654 (8).jpg: REAL (0.99834)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0444.jpg: REAL (0.99722)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0339 (4).jpg: REAL (0.99965)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0420 (7).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0058.jpg: REAL (0.99998)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0017 (2).jpg: REAL (0.98972)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0841 (2).jpg: REAL (0.99980)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0904 (6).jpg: REAL (0.99705)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0591 (3).jpg: REAL (0.62308)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0757 (8).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0748.jpg: REAL (0.59813)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0594 (7).jpg: REAL (0.99740)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
0255.jpg: REAL (0.97644)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0146 (7).jpg: REAL (0.99988)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0409 (7).jpg: REAL (0.99630)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0734 (9).jpg: REAL (0.99905)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
0523 (6).jpg: REAL (0.99874)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0017 (3).jpg: REAL (0.99960)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0433 (4).jpg: REAL (0.99985)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0763 (2).jpg: REAL (0.99547)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0303 (5).jpg: REAL (0.89607)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0368 (10).jpg: REAL (0.99996)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0349 (9).jpg: REAL (0.93491)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0087 (4).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0715 (9).jpg: REAL (0.99997)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
0084 (9).jpg: REAL (0.92240)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
0024 (8).jpg: REAL (0.94761)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0360 (6).jpg: REAL (0.99699)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0156 (4).jpg: REAL (0.72575)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0264 (3).jpg: REAL (0.99298)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0189 (8).jpg: REAL (0.86365)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0128.jpg: REAL (0.99994)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0495 (4).jpg: REAL (0.99971)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0297 (3).jpg: REAL (0.99962)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0612 (6).jpg: REAL (0.99784)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0544 (7).jpg: REAL (0.99714)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0024 (4).jpg: REAL (0.99981)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0897 (9).jpg: REAL (0.99552)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0786 (7).jpg: REAL (0.99866)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0019 (4).jpg: REAL (0.99887)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0243 (9).jpg: REAL (0.97313)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0187 (2).jpg: REAL (0.99936)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0248 (9).jpg: REAL (0.99961)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0923 (4).jpg: REAL (0.99994)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0633 (2).jpg: REAL (0.99506)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0399 (4).jpg: REAL (0.95546)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0828 (9).jpg: REAL (0.86459)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0803 (10).jpg: REAL (0.99919)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0400 (4).jpg: REAL (0.99951)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
0843 (8).jpg: REAL (0.99809)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0221 (2).jpg: REAL (0.99989)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0393 (7).jpg: REAL (0.99788)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0968 (6).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0142 (3).jpg: REAL (0.99269)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0176 (6).jpg: REAL (0.98622)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0042 (9).jpg: REAL (0.84978)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0184 (3).jpg: REAL (0.98122)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0228 (5).jpg: REAL (0.99062)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0035 (3).jpg: REAL (0.91465)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0655 (8).jpg: REAL (0.99665)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0298 (2).jpg: AI (0.47460)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0182 (3).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0585 (7).jpg: AI (0.41672)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0885 (7).jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0816 (8).jpg: REAL (0.98797)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0972 (4).jpg: REAL (0.99993)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0933 (7).jpg: REAL (0.99998)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0516 (5).jpg: REAL (0.99975)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0329 (9).jpg: REAL (0.99969)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0692 (4).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0973 (6).jpg: REAL (0.99902)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0185 (6).jpg: REAL (0.98906)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0945 (3).jpg: REAL (0.99512)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0000 (4).jpg: REAL (0.97213)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0522 (7).jpg: REAL (0.99986)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0700.jpg: REAL (0.99926)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
0095 (7).jpg: REAL (0.99999)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0207 (4).jpg: REAL (0.92257)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0818 (5).jpg: REAL (0.96944)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0371 (2).jpg: REAL (0.99813)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
0563 (8).jpg: REAL (0.99358)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0364.jpg: REAL (0.98334)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0649 (6).jpg: REAL (0.99991)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0477 (9).jpg: REAL (0.99957)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0017 (9).jpg: REAL (0.99990)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0831 (8).jpg: REAL (0.99683)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0494 (10).jpg: REAL (0.99997)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0405 (4).jpg: REAL (0.99986)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0922 (7).jpg: REAL (0.93704)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0904 (2).jpg: REAL (0.99342)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0164 (5).jpg: REAL (0.99970)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0795 (5).jpg: REAL (0.99846)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0738 (3).jpg: AI (0.17059)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
0956 (3).jpg: REAL (0.99505)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0671 (10).jpg: REAL (0.93256)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0853 (7).jpg: REAL (0.96229)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0246 (3).jpg: REAL (0.95693)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0916 (9).jpg: REAL (0.99990)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0159 (6).jpg: REAL (0.99954)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0417 (8).jpg: REAL (0.99768)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0456 (6).jpg: REAL (0.99911)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0389 (4).jpg: REAL (0.96869)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0396 (3).jpg: REAL (0.99549)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0299 (5).jpg: REAL (0.99993)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0737 (10).jpg: REAL (0.99752)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0037 (9).jpg: REAL (0.99980)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0798.jpg: REAL (0.50913)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
0284 (5).jpg: REAL (0.96874)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0049 (5).jpg: REAL (0.99598)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
0890 (3).jpg: REAL (0.99989)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0364 (6).jpg: REAL (0.99969)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
0753 (2).jpg: REAL (0.99442)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0896 (4).jpg: REAL (0.99983)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0246.jpg: REAL (1.00000)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
0751 (3).jpg: REAL (0.99520)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0631 (4).jpg: REAL (0.99982)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
0821 (6).jpg: REAL (0.99886)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0939 (7).jpg: REAL (0.98539)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
0918 (2).jpg: REAL (0.71106)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
0393 (9).jpg: REAL (0.98081)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

In [6]:
import os

model_dir = '/kaggle/working/models'
os.makedirs(model_dir, exist_ok=True)  # creates folder if it doesn't exist
print("Folder ready:", model_dir)

Folder ready: /kaggle/working/models

In [7]:
print("Min:", preds.min())
print("Max:", preds.max())
print("Mean:", preds.mean())

Min: 4.17222e-05
Max: 0.32913306
Mean: 0.059897617

In [8]:
loss, acc = model.evaluate(test_gen)
print("Test accuracy:", acc)

625/625 ━━━━━━━━━━━━━━━━━━━━ 53s 84ms/step - accuracy: 0.8723 - loss: 0.3326
Test accuracy: 0.910099983215332

In [9]:
preds = model.predict(test_gen)
labels = (preds > 0.5).astype(int)

print("Real predicted:", labels.sum())
print("AI predicted:", len(labels) - labels.sum())

625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step
Real predicted: 11066
AI predicted: 8934

In [10]:
from sklearn.metrics import confusion_matrix, classification_report

preds = model.predict(test_gen)
labels = (preds > 0.5).astype(int)

print(confusion_matrix(test_gen.classes, labels))
print(classification_report(test_gen.classes, labels))

625/625 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step
[[8568 1432]
 [ 366 9634]]
              precision    recall  f1-score   support

           0       0.96      0.86      0.91     10000
           1       0.87      0.96      0.91     10000

    accuracy                           0.91     20000
   macro avg       0.91      0.91      0.91     20000
weighted avg       0.91      0.91      0.91     20000

FINAL val_accuracy: 0.91

In [11]:
import os
os.listdir("/kaggle/working")

['models', 'predictions_ai.csv', 'predictions_real.csv', '__notebook__.ipynb']

In [12]:
import pandas as pd

df = pd.read_csv("/kaggle/working/predictions_real.csv")
df.head()

     image_name prediction  probability
0      0664.jpg       REAL     0.918776
1  0280 (6).jpg       REAL     0.632799
2  0816 (6).jpg       REAL     0.999316
3  0704 (5).jpg       REAL     0.999994
4  0896 (9).jpg       REAL     0.999574

In [13]:
import pandas as pd

df = pd.read_csv("/kaggle/working/predictions_ai.csv")
df.head()

     image_name prediction  probability
0   943 (5).jpg       REAL     0.966334
1   534 (7).jpg         AI     0.000013
2    81 (2).jpg         AI     0.092819
3   869 (9).jpg         AI     0.207322
4  610 (10).jpg         AI     0.000765